[2019-01-15 22:59:02,190] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29271282 (UptimeParser.py:25)
[2019-01-15 22:59:12,050] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124196890 (UptimeParser.py:25)
[2019-01-15 22:59:37,603] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 1575003600 (UptimeParser.py:25)
[2019-01-15 23:00:14,564] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29278518 (UptimeParser.py:25)
[2019-01-15 23:01:29,715] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124210659 (UptimeParser.py:25)
[2019-01-15 23:04:39,898] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124229678 (UptimeParser.py:25)
[2019-01-15 23:04:40,646] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29305127 (UptimeParser.py:25)
[2019-01-15 23:09:52,911] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124260978 (UptimeParser.py:25)
[2019-01-15 23:09:54,050] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29336464 (UptimeParser.py:25)
[2019-01-15 23:10:10,357] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124262724 (UptimeParser.py:25)
[2019-01-15 23:10:11,231] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29338184 (UptimeParser.py:25)
[2019-01-15 23:27:59,798] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124369667 (UptimeParser.py:27)
[2019-01-15 23:28:00,282] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29445093 (UptimeParser.py:27)
[2019-01-15 23:28:07,661] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124370451 (UptimeParser.py:27)
[2019-01-15 23:28:08,924] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29445952 (UptimeParser.py:27)
[2019-01-15 23:28:51,673] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124374855 (UptimeParser.py:27)
[2019-01-15 23:28:52,563] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29450317 (UptimeParser.py:27)
[2019-01-15 23:29:42,402] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124379927 (UptimeParser.py:27)
[2019-01-15 23:29:43,229] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29455385 (UptimeParser.py:27)
[2019-01-15 23:30:00,956] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124381782 (UptimeParser.py:27)
[2019-01-15 23:30:01,829] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29457243 (UptimeParser.py:27)
[2019-01-15 23:30:31,126] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124384799 (UptimeParser.py:27)
[2019-01-15 23:30:32,109] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29460272 (UptimeParser.py:27)
[2019-01-15 23:33:23,940] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124402083 (UptimeParser.py:27)
[2019-01-15 23:33:24,470] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29477509 (UptimeParser.py:27)
[2019-01-15 23:33:31,038] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:21)
[2019-01-15 23:34:47,234] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124410413 (UptimeParser.py:27)
[2019-01-15 23:34:47,749] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29485837 (UptimeParser.py:27)
[2019-01-15 23:34:54,447] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:21)
[2019-01-15 23:35:26,911] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124414376 (UptimeParser.py:27)
[2019-01-15 23:35:28,097] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29489871 (UptimeParser.py:27)
[2019-01-15 23:35:29,300] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124414615 (UptimeParser.py:27)
[2019-01-15 23:40:01,501] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124441836 (UptimeParser.py:28)
[2019-01-15 23:40:02,157] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29517277 (UptimeParser.py:28)
[2019-01-15 23:40:02,796] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124441967 (UptimeParser.py:28)
[2019-01-15 23:40:53,501] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124447037 (UptimeParser.py:28)
[2019-01-15 23:40:54,094] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29522471 (UptimeParser.py:28)
[2019-01-15 23:40:54,609] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124447148 (UptimeParser.py:28)
[2019-01-15 23:41:04,849] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124448172 (UptimeParser.py:28)
[2019-01-15 23:41:05,426] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29523604 (UptimeParser.py:28)
[2019-01-15 23:41:06,065] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124448294 (UptimeParser.py:28)
[2019-01-15 23:42:52,574] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124458943 (UptimeParser.py:28)
[2019-01-15 23:42:53,775] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29534437 (UptimeParser.py:28)
[2019-01-15 23:42:54,962] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124459182 (UptimeParser.py:28)
[2019-01-15 23:42:56,179] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240477774 (UptimeParser.py:28)
[2019-01-15 23:45:35,115] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124475197 (UptimeParser.py:28)
[2019-01-15 23:45:36,082] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 29550667 (UptimeParser.py:28)
[2019-01-15 23:45:37,299] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 124475414 (UptimeParser.py:28)
[2019-01-15 23:45:38,718] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240494024 (UptimeParser.py:28)
[2019-01-15 23:45:39,779] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 10400 (UptimeParser.py:28)
[2019-01-15 23:45:58,096] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240495967 (UptimeParser.py:28)
[2019-01-15 23:46:05,038] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:22)
[2019-01-15 23:47:07,753] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240502932 (UptimeParser.py:28)
[2019-01-15 23:47:14,731] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:22)
[2019-01-15 23:48:27,124] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240510868 (UptimeParser.py:28)
[2019-01-15 23:48:33,988] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:22)
[2019-01-15 23:50:24,620] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240522618 (UptimeParser.py:28)
[2019-01-15 23:50:31,594] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:22)
[2019-01-15 23:50:31,594] [   ERROR] --- Cannot get uptime from: demo.snmplabs.com (UptimeParser.py:70)
[2019-01-15 23:50:31,594] [   ERROR] --- Cannot get uptime from: broken.com (UptimeParser.py:70)
[2019-01-15 23:50:47,724] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240524929 (UptimeParser.py:28)
[2019-01-15 23:50:54,792] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:22)
[2019-01-15 23:50:54,792] [   ERROR] --- Cannot get uptime from: demo.snmplabs.com (UptimeParser.py:70)
[2019-01-15 23:50:54,792] [   ERROR] --- Cannot get uptime from: broken.com (UptimeParser.py:70)
[2019-01-15 23:50:58,115] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240525968 (UptimeParser.py:28)
[2019-01-15 23:51:05,073] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:22)
[2019-01-15 23:51:05,073] [   ERROR] --- Cannot get uptime from: demo.snmplabs.com (UptimeParser.py:70)
[2019-01-15 23:51:05,073] [   ERROR] --- Cannot get uptime from: broken.com (UptimeParser.py:70)
[2019-01-15 23:51:16,259] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240527782 (UptimeParser.py:28)
[2019-01-15 23:51:23,091] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:22)
[2019-01-15 23:51:23,091] [   ERROR] --- Cannot get uptime from: demo.snmplabs.com (UptimeParser.py:70)
[2019-01-15 23:51:23,091] [   ERROR] --- Cannot get uptime from: broken.com (UptimeParser.py:70)
[2019-01-15 23:52:01,470] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240532302 (UptimeParser.py:28)
[2019-01-15 23:52:08,350] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:22)
[2019-01-15 23:52:08,350] [   ERROR] --- Cannot get uptime from: demo.snmplabs.com (UptimeParser.py:72)
[2019-01-15 23:52:08,350] [   ERROR] --- Cannot get uptime from: broken.com (UptimeParser.py:72)
[2019-01-15 23:52:32,722] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240535430 (UptimeParser.py:28)
[2019-01-15 23:52:39,648] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:22)
[2019-01-15 23:52:39,648] [   ERROR] --- Cannot get uptime from: demo.snmplabs.com (UptimeParser.py:72)
[2019-01-15 23:52:39,648] [   ERROR] --- Cannot get uptime from: broken.com (UptimeParser.py:72)
[2019-01-15 23:52:58,343] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240537991 (UptimeParser.py:28)
[2019-01-15 23:53:05,207] [   ERROR] --- No SNMP response received before timeout (UptimeParser.py:22)
[2019-01-15 23:53:05,207] [   ERROR] --- Cannot get uptime from: demo.snmplabs.com (UptimeParser.py:73)
[2019-01-15 23:53:24,696] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240540626 (UptimeParser.py:28)
[2019-01-15 23:53:24,696] [   ERROR] --- Cannot get uptime from: demo.snmplabs.com (UptimeParser.py:73)
[2019-01-15 23:54:17,333] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240545889 (UptimeParser.py:28)
[2019-01-15 23:54:34,868] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 240547643 (UptimeParser.py:28)
[2019-01-15 23:54:35,336] [   ERROR] --- SNMPv2-MIB::sysUpTime.0 = 64000 (UptimeParser.py:28)
